services:
  fluentbit:
    image: fluent/fluent-bit:3.1.9
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - LOKI_HOST=${LOKI_HOST}
      - LOKI_USER=${LOKI_USER}
      - LOKI_PASSWORD=${LOKI_PASSWORD}
    volumes:
      - type: bind
        source: ./scripts/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - asynqmon
    volumes:
      - type: bind
        source: ./scripts/nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt

  backend:
    build:
      context: .
      dockerfile: http.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - fluentbit
    environment:
      - REDIS_URL=${REDIS_URL}
    logging:
      driver: fluentd
      options:
        tag: http-service
        fluentd-sub-second-precision: "true"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - redis
      - fluentbit
    environment:
      - REDIS_URL=${REDIS_URL}
    logging:
      driver: fluentd
      options:
        tag: worker-service
        fluentd-sub-second-precision: "true"

  asynqmon:
    build:
      context: .
      dockerfile: asynqmon.Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - fluentbit
    environment:
      - REDIS_URL=${REDIS_URL}
    logging:
      driver: fluentd
      options:
        tag: http-service
        fluentd-sub-second-precision: "true"
