services:
  fluentbit:
    env_file: ".compose.env"
    image: fluent/fluent-bit:3.1.9
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - demi_masa
    volumes:
      - type: bind
        source: ./fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - demi_masa

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - demi_masa
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt

networks:
  demi_masa:
    external: true
