services:
  fluentbit:
    image: fluent/fluent-bit:3.1.9
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - type: bind
        source: ./internal/config/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"

  http:
    build:
      context: .
      dockerfile: http.Dockerfile
    ports:
      - "80:80"
    environment:
      - REDIS_URL=${REDIS_URL}
    logging:
      driver: fluentd
      options:
        tag: http-service
        fluentd-sub-second-precision: "true"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
    logging:
      driver: fluentd
      options:
        tag: worker-service
        fluentd-sub-second-precision: "true"
