services:
  asynqmon:
    image: mdayat/demi-masa-asynqmon:latest
    ports:
      - "9090:9090"
    environment:
      - REDIS_URL=${REDIS_URL}
    networks:
      - demi_masa
    logging:
      driver: fluentd
      options:
        tag: asynqmon-service
        fluentd-sub-second-precision: "true"

networks:
  demi_masa:
    external: true
