// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreatePrayers implements pgx.CopyFromSource.
type iteratorForCreatePrayers struct {
	rows                 []CreatePrayersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePrayers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePrayers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].Name,
		r.rows[0].Year,
		r.rows[0].Month,
		r.rows[0].Day,
	}, nil
}

func (r iteratorForCreatePrayers) Err() error {
	return nil
}

func (q *Queries) CreatePrayers(ctx context.Context, arg []CreatePrayersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"prayer"}, []string{"id", "user_id", "name", "year", "month", "day"}, &iteratorForCreatePrayers{rows: arg})
}
