services:
  worker:
    env_file: "../.compose.env"
    image: mdayat/demi-masa-worker:${WORKER_IMAGE_TAG}
    networks:
      - demi_masa
    logging:
      driver: fluentd
      options:
        tag: worker-service
        fluentd-sub-second-precision: "true"

networks:
  demi_masa:
    external: true
