services:
  worker:
    build: .
    environment:
      - REDIS_URL=${REDIS_URL}
    networks:
      - demi_masa
    logging:
      driver: fluentd
      options:
        tag: worker-service
        fluentd-sub-second-precision: "true"

networks:
  demi_masa:
    external: true
