name: Web Production Deployment

on:
  push:
    paths:
      - "web/**"
    branches:
      - main
  pull_request:
    paths:
      - "web/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add environment variables and secrets
        run: |
          echo "${{ secrets.WEB_ENV_FILE }}" > web/.env
          echo "${{ secrets.SERVICE_ACCOUNT_FILE }}" > web/service-account-file.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        run: |
          cd web
          docker build -t "${{ vars.DOCKERHUB_USERNAME }}"/demi-masa-web:latest .
          docker push "${{ vars.DOCKERHUB_USERNAME }}"/demi-masa-web:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_vps
          chmod 600 ~/.ssh/id_ed25519_vps
          echo -e "Host "${{ secrets.VPS_IP }}"\n\tUser "${{ secrets.VPS_USERNAME }}"\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_ed25519_vps" >> ~/.ssh/config

      - name: Deploy to VPS
        run: |
          ssh "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}" "mkdir -p /app/web"
          scp web/compose.yaml "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}":/app/web
          ssh "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}" "cd /app/web && docker compose up -d"
