name: Web Production Deployment

on:
  push:
    paths:
      - "web/**"
    branches:
      - main
  pull_request:
    paths:
      - "web/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set APP_TAG
        id: app_tag_setter
        run: echo "app_tag=$(git tag -l --sort=-v:refname "web*" | head -n 1 | sed 's/web\/v//')" >> $GITHUB_OUTPUT

      - name: Add secrets
        env:
          JSON: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        run: |
          echo "${{ secrets.WEB_ENV_FILE }}" > web/.env
          echo "$JSON" > web/service-account-file.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          cd web
          docker build -t "${{ vars.DOCKERHUB_USERNAME }}"/demi-masa-web:${{ steps.app_tag_setter.outputs.app_tag }} .
          docker push "${{ vars.DOCKERHUB_USERNAME }}"/demi-masa-web:${{ steps.app_tag_setter.outputs.app_tag }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            export WEB_IMAGE_TAG=${{ steps.app_tag_setter.outputs.app_tag }}
            cd /app/web
            docker compose down
            docker compose up -d
