services:
  web:
    env_file: "../.compose.env"
    image: mdayat/demi-masa-web:${WEB_IMAGE_TAG}
    ports:
      - "8080:8080"
    networks:
      - demi_masa
    logging:
      driver: fluentd
      options:
        tag: web-service
        fluentd-sub-second-precision: "true"

networks:
  demi_masa:
    external: true
